import { Category, Coupon, Dish, Restaurant, Review } from './types'

export const CITIES = [
  'Chennai',
  'Coimbatore',
  'Madurai',
  'Salem',
  'Trichy',
  'Tirunelveli',
  'Erode',
  'Thanjavur',
] as const

export const CATEGORIES: { label: Category; icon: string; countHint: string }[] = [
  { label: 'All cravings', icon: '✦', countHint: 'All authentic picks' },
  { label: 'Tiffin', icon: '◉', countHint: 'Idli, Dosa, Vadai & Pongal' },
  { label: 'Biryani', icon: '◈', countHint: 'Seeraga samba & Dum' },
  { label: 'Meals', icon: '✺', countHint: 'Banana leaf meals & curries' },
  { label: 'Street food', icon: '◇', countHint: 'Bun Parotta, Kothu, Kalakki' },
  { label: 'Sweets', icon: '●', countHint: 'Halwa, Kesari & Payasam' },
  { label: 'Drinks', icon: '○', countHint: 'Degree Coffee & Jigarthanda' },
]

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Paati Veedu',
    tagline: 'Grandmother’s heritage recipes prepared with pure cold-pressed gingelly oil & hand-ground spices',
    area: 'Mylapore',
    city: 'Chennai',
    rating: 4.9,
    reviewsCount: '2.4k+',
    time: '15–20 min',
    distance: '1.8 km',
    priceForTwo: 160,
    tag: 'Home-style Heritage',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=85',
    isPureVeg: true,
    specialty: 'Ghee Podi Idli, Pongal & Filter Coffee',
    isFeatured: true,
  },
  {
    id: 'rest-2',
    name: 'Kongu Mess',
    tagline: 'Authentic Kongu Nadu village traditions with freshly roasted rustic spices',
    area: 'RS Puram',
    city: 'Coimbatore',
    rating: 4.8,
    reviewsCount: '1.8k+',
    time: '20–25 min',
    distance: '2.4 km',
    priceForTwo: 240,
    tag: 'Kongu Special',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=85',
    isPureVeg: false,
    specialty: 'Nattu Kozhi Curry & Banana Leaf Meals',
    isFeatured: true,
  },
  {
    id: 'rest-3',
    name: 'Madurai Bun Parotta Kadai',
    tagline: 'Legendary Madurai night food stall with hand-kneaded flaky puffed bun parottas',
    area: 'Anna Nagar',
    city: 'Madurai',
    rating: 4.8,
    reviewsCount: '3.1k+',
    time: '12–18 min',
    distance: '1.5 km',
    priceForTwo: 130,
    tag: 'Late Night Legend',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85',
    isPureVeg: false,
    specialty: 'Bun Parotta, Egg Kothu & Kari Dosa',
    isFeatured: true,
  },
  {
    id: 'rest-4',
    name: 'Dindigul Thalappakatti',
    tagline: 'Since 1957. Legendary Seeraga Samba short grain dum biryani steeped in secret spices',
    area: 'T Nagar',
    city: 'Chennai',
    rating: 4.7,
    reviewsCount: '5.2k+',
    time: '20–25 min',
    distance: '2.9 km',
    priceForTwo: 320,
    tag: 'Biryani Royalty',
    image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=900&q=85',
    isPureVeg: false,
    specialty: 'Thalappakatti Mutton & Chicken Biryani',
    isFeatured: true,
  },
  {
    id: 'rest-5',
    name: 'Saravana Bhavan',
    tagline: 'World-renowned South Indian vegetarian breakfast and golden crispy roasted dosas',
    area: 'Adyar',
    city: 'Chennai',
    rating: 4.8,
    reviewsCount: '6.5k+',
    time: '15–20 min',
    distance: '1.6 km',
    priceForTwo: 140,
    tag: 'Pure Veg Pioneer',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=900&q=85',
    isPureVeg: true,
    specialty: 'Golden Masala Dosa & Medu Vadai',
  },
  {
    id: 'rest-6',
    name: 'Kumbakonam Degree Coffee',
    tagline: 'Pure cow milk first-degree decoction brewed in traditional brass filters',
    area: 'Trichy Road',
    city: 'Salem',
    rating: 4.7,
    reviewsCount: '980+',
    time: '10–15 min',
    distance: '1.2 km',
    priceForTwo: 70,
    tag: 'Fresh Brews',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=85',
    isPureVeg: true,
    specialty: 'Degree Filter Coffee & Davarah Tumbler Brews',
  },
  {
    id: 'rest-7',
    name: 'Ambur Star Biryani',
    tagline: 'Traditional Nawab heritage dum biryani served with brinjal pachadi & ennai kathirikai',
    area: 'Gandhipuram',
    city: 'Coimbatore',
    rating: 4.8,
    reviewsCount: '2.7k+',
    time: '20–25 min',
    distance: '2.2 km',
    priceForTwo: 340,
    tag: 'Nawabi Heritage',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=85',
    isPureVeg: false,
    specialty: 'Seeraga Samba Mutton Dum Biryani',
  },
  {
    id: 'rest-8',
    name: 'Famous Madurai Jigarthanda',
    tagline: 'The royal cooler created for Nayakar kings with almond gum, nannari syrup & pure basundi',
    area: 'South Gate',
    city: 'Madurai',
    rating: 4.9,
    reviewsCount: '4.8k+',
    time: '10–15 min',
    distance: '0.9 km',
    priceForTwo: 120,
    tag: 'GI Tag Heritage',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=85',
    isPureVeg: true,
    specialty: 'Special Basundi Jigarthanda',
  },
  {
    id: 'rest-9',
    name: 'Salem Thattu Kadai',
    tagline: 'Famous Salem roadside street cart snacks, crispy mushroom fry and fresh kalakki',
    area: 'Hasthampatti',
    city: 'Salem',
    rating: 4.6,
    reviewsCount: '1.2k+',
    time: '15–20 min',
    distance: '1.8 km',
    priceForTwo: 110,
    tag: 'Street Bites',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=900&q=85',
    isPureVeg: false,
    specialty: 'Salem Kaalan Fry & Muttai Kalakki',
  },
  {
    id: 'rest-10',
    name: 'Thanjavur Sapadu',
    tagline: 'Grand royal Maratha-Chola leaf banquet with hand-churned mor kuzhambu & payasam',
    area: 'Medical College Road',
    city: 'Thanjavur',
    rating: 4.9,
    reviewsCount: '1.5k+',
    time: '25–30 min',
    distance: '2.5 km',
    priceForTwo: 260,
    tag: 'Chola Feast',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=85',
    isPureVeg: true,
    specialty: 'Authentic 18-course Banana Leaf Meals',
  },
  {
    id: 'rest-11',
    name: 'Iruttu Kadai Halwa Store',
    tagline: 'Legendary Thamirabarani river water wheat halwa slow-cooked in pure country cow ghee',
    area: 'Nellai Town',
    city: 'Tirunelveli',
    rating: 4.9,
    reviewsCount: '5.9k+',
    time: '15–20 min',
    distance: '1.4 km',
    priceForTwo: 110,
    tag: 'Iconic Sweets',
    image: 'https://images.unsplash.com/photo-1571167530149-c8f32e2b6f6d?auto=format&fit=crop&w=900&q=85',
    isPureVeg: true,
    specialty: 'Warm Tirunelveli Ghee Halwa',
  },
  {
    id: 'rest-12',
    name: 'Rockfort Tiffin Club',
    tagline: 'Historic Trichy town eatery famous for stone-ground soft idlis and fiery milagai podi',
    area: 'Main Guard Gate',
    city: 'Trichy',
    rating: 4.7,
    reviewsCount: '2.1k+',
    time: '15–20 min',
    distance: '1.9 km',
    priceForTwo: 120,
    tag: 'Heritage Tiffin',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=85',
    isPureVeg: true,
    specialty: 'Trichy Podi Uthappam & Vadai',
  },
]

export const DISHES: Dish[] = [
  // --- TIFFIN CATEGORY ---
  {
    id: 'dish-1',
    name: 'Ghee Podi Idli (14 mini)',
    tamilName: 'நெய் பொடி இட்லி',
    restaurant: 'Paati Veedu',
    city: 'Chennai',
    category: 'Tiffin',
    price: 65,
    marketPrice: 110,
    kcal: 320,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    description: 'Button mini idlis tossed generously in fragrant pure cow ghee and stone-pounded spicy gun powder with roasted lentils, curry leaves, and coconut chutney.',
    portion: '14 mini idlis + 3 chutneys',
    protein: 11,
    carbs: 46,
    fat: 7,
    availableAddons: [
      { name: 'Extra Gunpowder Podi', price: 10 },
      { name: 'Pure Country Ghee Drizzle', price: 15 },
      { name: 'Bowl of Drumstick Sambar', price: 15 },
    ],
    tags: ['Traditional', 'Bestseller', 'Breakfast Hero'],
  },
  {
    id: 'dish-2',
    name: 'Golden Ghee Masala Dosa',
    tamilName: 'நெய் மசாலா தோசை',
    restaurant: 'Saravana Bhavan',
    city: 'Chennai',
    category: 'Tiffin',
    price: 75,
    marketPrice: 130,
    kcal: 380,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    description: 'Crispy golden fermented crepe roasted with pure butter, stuffed with spiced mashed potato herb masala, served with tomato chutney, coconut chutney and hot tiffin sambar.',
    portion: '1 large crisp dosa + 3 chutneys + sambar',
    protein: 10,
    carbs: 52,
    fat: 12,
    availableAddons: [
      { name: 'Extra Potato Masala Cup', price: 15 },
      { name: 'Mysore Red Chutney Spread', price: 10 },
      { name: 'Degree Coffee Shot', price: 20 },
    ],
    tags: ['Crispy Favorite', 'All-Day Hit'],
  },
  {
    id: 'dish-3',
    name: 'Crispy Plain Roast Dosa',
    tamilName: 'நெய் ரோஸ்ட் தோசை',
    restaurant: 'Saravana Bhavan',
    city: 'Chennai',
    category: 'Tiffin',
    price: 55,
    marketPrice: 95,
    kcal: 290,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Paper-thin golden roasted plain dosa with delightful crunch, paired with freshly ground green mint chutney, red chilli coconut chutney and sambar.',
    portion: '1 jumbo crispy dosa',
    protein: 7,
    carbs: 45,
    fat: 8,
    availableAddons: [
      { name: 'Pure Country Ghee Drizzle', price: 15 },
      { name: 'Gunpowder Podi Cup', price: 10 },
    ],
    tags: ['Light & Crispy', 'Classic'],
  },
  {
    id: 'dish-4',
    name: 'Steamed Kanchipuram Idli (2 pcs)',
    tamilName: 'காஞ்சிபுரம் கோவில் இட்லி',
    restaurant: 'Saravana Bhavan',
    city: 'Chennai',
    category: 'Tiffin',
    price: 45,
    marketPrice: 75,
    kcal: 220,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Ancient temple-style steamed idlis flavored with crushed black pepper, cumin seeds, dry ginger and curry leaves. Steamed in traditional mandharai leaf cups.',
    portion: '2 large soft idlis + coconut chutney',
    protein: 8,
    carbs: 38,
    fat: 3,
    availableAddons: [
      { name: 'Crispy Medu Vadai (1 pc)', price: 15 },
      { name: 'Extra Drumstick Sambar', price: 15 },
    ],
    tags: ['Temple Recipe', 'Light & Healthy'],
  },
  {
    id: 'dish-5',
    name: 'Ven Pongal & Medu Vadai Combo',
    tamilName: 'வெண் பொங்கல் வடை',
    restaurant: 'Paati Veedu',
    city: 'Chennai',
    category: 'Tiffin',
    price: 60,
    marketPrice: 105,
    kcal: 390,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Mild',
    description: 'Silken tender rice and moong dal tempered with golden fried cashews, peppercorns, cumin and pure ghee, paired with 1 piping hot crunchy medu vadai.',
    portion: '1 bowl pongal + 1 crispy vadai',
    protein: 12,
    carbs: 56,
    fat: 11,
    availableAddons: [
      { name: 'Extra Crunchy Medu Vadai', price: 18 },
      { name: 'Cashew Butter Glaze', price: 15 },
    ],
    tags: ['Paati Veedu Special', 'Comfort Food'],
  },
  {
    id: 'dish-6',
    name: 'Crispy Medu Vadai (2 pcs)',
    tamilName: 'உளுந்து மெது வடை',
    restaurant: 'Saravana Bhavan',
    city: 'Chennai',
    category: 'Tiffin',
    price: 35,
    marketPrice: 60,
    kcal: 230,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Crispy outside, fluffy inside black gram fritters seasoned with fresh ginger, cracked pepper, and curry leaves. Served hot with fresh coconut chutney.',
    portion: '2 crispy vadais',
    protein: 9,
    carbs: 24,
    fat: 10,
    availableAddons: [
      { name: 'Dip in Hot Sambar Bowl', price: 15 },
      { name: 'Spicy Milagai Chutney', price: 10 },
    ],
    tags: ['Crunchy Delight', 'Tea Companion'],
  },
  {
    id: 'dish-7',
    name: 'Rockfort Milagai Podi Uthappam',
    tamilName: 'திருச்சி பொடி ஊத்தப்பம்',
    restaurant: 'Rockfort Tiffin Club',
    city: 'Trichy',
    category: 'Tiffin',
    price: 65,
    marketPrice: 110,
    kcal: 310,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Medium',
    description: 'Thick, spongy fermented rice pancake smeared with spicy roasted lentil podi, diced shallots, and fresh coriander. Served with 2 house chutneys.',
    portion: '1 thick uthappam',
    protein: 9,
    carbs: 48,
    fat: 7,
    availableAddons: [
      { name: 'Extra Gunpowder Podi', price: 10 },
      { name: 'Ghee Ladle Bath', price: 15 },
    ],
    tags: ['Trichy Special', 'Fluffy & Spiced'],
  },

  // --- BIRYANI CATEGORY ---
  {
    id: 'dish-8',
    name: 'Dindigul Thalappakatti Chicken Biryani',
    tamilName: 'திண்டுக்கல் சிக்கன் பிரியாணி',
    restaurant: 'Dindigul Thalappakatti',
    city: 'Chennai',
    category: 'Biryani',
    price: 160,
    marketPrice: 260,
    kcal: 640,
    image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=800&q=85',
    isVeg: false,
    isBestseller: true,
    spiceLevel: 'Medium',
    description: 'Iconic Seeraga Samba short-grain rice cooked on wood fire with succulent country chicken, crushed green chillies, fresh mint, dalcha, and onion raita.',
    portion: '450g authentic portion + dalcha + raita + egg',
    protein: 34,
    carbs: 78,
    fat: 19,
    availableAddons: [
      { name: 'Boiled Farm Egg (1 pc)', price: 12 },
      { name: 'Spicy Chicken 65 (3 pcs)', price: 45 },
      { name: 'Extra Onion Pachadi', price: 12 },
    ],
    tags: ['Heritage Legend', 'Seeraga Samba', 'Bestseller'],
  },
  {
    id: 'dish-9',
    name: 'Ambur Mutton Dum Biryani',
    tamilName: 'ஆம்பூர் மட்டன் பிரியாணி',
    restaurant: 'Ambur Star Biryani',
    city: 'Coimbatore',
    category: 'Biryani',
    price: 210,
    marketPrice: 320,
    kcal: 690,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=85',
    isVeg: false,
    isBestseller: true,
    spiceLevel: 'Medium',
    description: 'Nawabi Arcot style biryani made with Seeraga Samba rice, curd-marinated tender mutton cubes, and subtle whole spices, served with signature sour brinjal gravy (Ennai Kathirikai).',
    portion: '500g biryani + ennai kathirikai + raita',
    protein: 36,
    carbs: 76,
    fat: 22,
    availableAddons: [
      { name: 'Ennai Kathirikai Extra Bowl', price: 20 },
      { name: 'Boiled Farm Egg', price: 12 },
    ],
    tags: ['Ambur Legend', 'Slow Cooked Dum'],
  },
  {
    id: 'dish-10',
    name: 'Chettinad Kozhi Biryani',
    tamilName: 'செட்டிநாடு கோழி பிரியாணி',
    restaurant: 'Kongu Mess',
    city: 'Coimbatore',
    category: 'Biryani',
    price: 175,
    marketPrice: 270,
    kcal: 620,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=85',
    isVeg: false,
    spiceLevel: 'Fiery',
    description: 'Chettinad stone-ground black pepper and shallot infused biryani cooked with tender chicken pieces, star anise, fennel, and served with spiced chicken salna.',
    portion: '450g spicy biryani + pepper salna',
    protein: 32,
    carbs: 74,
    fat: 18,
    availableAddons: [
      { name: 'Pepper Chicken Fry (4 pcs)', price: 50 },
      { name: 'Egg Omelette', price: 20 },
    ],
    tags: ['Chettinad Spiced', 'Fiery Aroma'],
  },
  {
    id: 'dish-11',
    name: 'Seeraga Samba Kuska with Salna',
    tamilName: 'குஸ்கா பிரியாணி சாதம்',
    restaurant: 'Madurai Bun Parotta Kadai',
    city: 'Madurai',
    category: 'Biryani',
    price: 90,
    marketPrice: 145,
    kcal: 480,
    image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Medium',
    description: 'Fragrant Seeraga Samba biryani rice slow-cooked in spiced broth with ghee, mint, and whole cloves without meat pieces. Served with rich Madurai salna and raita.',
    portion: '400g flavored rice + salna + raita',
    protein: 10,
    carbs: 70,
    fat: 12,
    availableAddons: [
      { name: 'Boiled Egg (1 pc)', price: 12 },
      { name: 'Chicken Salna Gravy Bowl', price: 25 },
    ],
    tags: ['Comfort Biryani', 'Budget Friendly'],
  },

  // --- MEALS CATEGORY ---
  {
    id: 'dish-12',
    name: 'Kongu Banana Leaf Mini Meals',
    tamilName: 'கொங்கு வாழை இலை சாப்பாடு',
    restaurant: 'Kongu Mess',
    city: 'Coimbatore',
    category: 'Meals',
    price: 120,
    marketPrice: 190,
    kcal: 460,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    description: 'Pure Kongu farm plate: Ponni steamed rice, Kovilur paruppu podi with ghee, vatha kuzhambu, tomato rasam, curd, beetroot poriyal, kootu, crunchy appalam and payasam.',
    portion: 'Complete meal box for 1 person',
    protein: 14,
    carbs: 78,
    fat: 8,
    availableAddons: [
      { name: 'Appalam & Mango Thokku Pack', price: 10 },
      { name: 'Spicy Kongu Potato Roast', price: 25 },
    ],
    tags: ['Balanced', 'No Preservatives', 'Vegetarian Feast'],
  },
  {
    id: 'dish-13',
    name: 'Kongu Nattu Kozhi Curry',
    tamilName: 'நாட்டுக்கோழி குழம்பு',
    restaurant: 'Kongu Mess',
    city: 'Coimbatore',
    category: 'Meals',
    price: 165,
    marketPrice: 250,
    kcal: 510,
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=800&q=85',
    isVeg: false,
    spiceLevel: 'Fiery',
    description: 'Free-range country chicken slow simmered in an aromatic stone-ground shallot, dry guntur chilli, and fresh coriander spice paste.',
    portion: 'Serves 1–2 with rich gravy',
    protein: 34,
    carbs: 12,
    fat: 17,
    availableAddons: [
      { name: 'Hot Parotta (2 pcs)', price: 35 },
      { name: 'Steamed Rice Portion', price: 25 },
    ],
    tags: ['Kongu Authentic', 'High Protein', 'Spicy'],
  },
  {
    id: 'dish-14',
    name: 'Thanjavur Full Banana Leaf Meals',
    tamilName: 'தஞ்சாவூர் ராஜ சாப்பாடு',
    restaurant: 'Thanjavur Sapadu',
    city: 'Thanjavur',
    category: 'Meals',
    price: 135,
    marketPrice: 210,
    kcal: 490,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Medium',
    description: 'Authentic royal Chola meal: Steamed rice, Kumbakonam Kadappa, Mor Kuzhambu, Keerai Kootu, Urulai Roast, Poondu Rasam, Buttermilk, and Vermicelli Payasam.',
    portion: 'Full leaf banquet packed in eco-friendly leaves',
    protein: 15,
    carbs: 82,
    fat: 9,
    availableAddons: [
      { name: 'Crispy Vazhaipoo Vadai (2 pcs)', price: 25 },
      { name: 'Poondu (Garlic) Thokku Cup', price: 12 },
    ],
    tags: ['Full Leaf Feast', 'Pure Heritage'],
  },
  {
    id: 'dish-15',
    name: 'Curd Rice & Mor Milagai',
    tamilName: 'தயிர் சாதம் மோர் மிளகாய்',
    restaurant: 'Paati Veedu',
    city: 'Chennai',
    category: 'Meals',
    price: 50,
    marketPrice: 85,
    kcal: 260,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Homestyle velvety curd rice tempered with mustard, ginger, green chillies and curry leaves, topped with roasted cashews and served with sun-dried Mor Milagai.',
    portion: '1 comforting bowl + pickle',
    protein: 8,
    carbs: 38,
    fat: 6,
    availableAddons: [
      { name: 'Crispy Appalam', price: 8 },
      { name: 'Vadumangai Tender Mango Pickle', price: 12 },
    ],
    tags: ['Light & Cooling', 'Gut Friendly'],
  },

  // --- STREET FOOD CATEGORY ---
  {
    id: 'dish-16',
    name: 'Madurai Bun Parotta (2 pcs) with Salna',
    tamilName: 'மதுரை பன் பரோட்டா சால்னா',
    restaurant: 'Madurai Bun Parotta Kadai',
    city: 'Madurai',
    category: 'Street food',
    price: 50,
    marketPrice: 90,
    kcal: 460,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    description: 'Soft, multi-layered puffed round golden parottas shallow-fried to perfection, served steaming hot with spiced Madurai vegetable salna and coconut raita.',
    portion: '2 bun parottas + bowl of hot salna',
    protein: 9,
    carbs: 62,
    fat: 15,
    availableAddons: [
      { name: 'Extra Bun Parotta (1 pc)', price: 22 },
      { name: 'Chicken Salna Upgrade', price: 20 },
      { name: 'Muttai Kalakki', price: 30 },
    ],
    tags: ['Madurai Iconic', 'Flaky & Soft', 'Night Stall Star'],
  },
  {
    id: 'dish-17',
    name: 'Street-Style Egg Kothu Parotta',
    tamilName: 'முட்டை கொத்து பரோட்டா',
    restaurant: 'Madurai Bun Parotta Kadai',
    city: 'Madurai',
    category: 'Street food',
    price: 95,
    marketPrice: 160,
    kcal: 520,
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=800&q=85',
    isVeg: false,
    isBestseller: true,
    spiceLevel: 'Fiery',
    description: 'Flaky parotta shredded and vigorously beaten on hot iron tawa with scrambled farm eggs, shallots, curry leaves, crushed black pepper, and rich salna gravy.',
    portion: 'Generous single plate',
    protein: 22,
    carbs: 58,
    fat: 18,
    availableAddons: [
      { name: 'Extra Egg Scramble', price: 15 },
      { name: 'Side Pepper Salna Cup', price: 18 },
    ],
    tags: ['Street Hit', 'Madurai Style', 'Spicy'],
  },
  {
    id: 'dish-18',
    name: 'Madurai Kari Dosa (Meat Feast)',
    tamilName: 'மதுரை காரி தோசை',
    restaurant: 'Madurai Bun Parotta Kadai',
    city: 'Madurai',
    category: 'Street food',
    price: 140,
    marketPrice: 220,
    kcal: 480,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=85',
    isVeg: false,
    spiceLevel: 'Fiery',
    description: 'Three-tiered Madurai culinary wonder: Thick soft dosa layered with beaten egg, spicy minced mutton chukka, and roasted pepper salna.',
    portion: '1 hearty layered kari dosa',
    protein: 28,
    carbs: 44,
    fat: 16,
    availableAddons: [
      { name: 'Spicy Pepper Salna Cup', price: 18 },
      { name: 'Ghee Crisp Top Crust', price: 15 },
    ],
    tags: ['Madurai Specialty', 'High Protein'],
  },
  {
    id: 'dish-19',
    name: 'Salem Crispy Kaalan Mushroom Fry',
    tamilName: 'சேலம் காளான் ஃப்ரை',
    restaurant: 'Salem Thattu Kadai',
    city: 'Salem',
    category: 'Street food',
    price: 55,
    marketPrice: 95,
    kcal: 270,
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Fiery',
    description: 'Iconic Salem evening roadside snack: Button mushrooms coated in crunchy batter, tossed with spicy pepper-garlic sauce, fresh coriander, onions and lemon.',
    portion: '1 generous evening basket',
    protein: 8,
    carbs: 34,
    fat: 8,
    availableAddons: [
      { name: 'Extra Crunchy Onion & Lemon', price: 8 },
      { name: 'Spicy Masala Gravy Drizzle', price: 12 },
    ],
    tags: ['Salem Specialty', 'Crispy & Tangy'],
  },
  {
    id: 'dish-20',
    name: 'Salem Muttai Kalakki (2 pcs)',
    tamilName: 'சேலம் முட்டை கலக்கி',
    restaurant: 'Salem Thattu Kadai',
    city: 'Salem',
    category: 'Street food',
    price: 35,
    marketPrice: 60,
    kcal: 200,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=85',
    isVeg: false,
    spiceLevel: 'Medium',
    description: 'Soft-folded creamy egg pocket gently seared on tawa with rich mutton salna, crushed black pepper, and curry leaves. Liquid velvety center.',
    portion: '2 kalakki pillows',
    protein: 15,
    carbs: 4,
    fat: 13,
    availableAddons: [
      { name: 'Pepper Salna Drizzle', price: 10 },
      { name: 'Extra Egg Fold', price: 15 },
    ],
    tags: ['Quick Comfort', 'Street Classic'],
  },

  // --- SWEETS CATEGORY ---
  {
    id: 'dish-21',
    name: 'Tirunelveli Warm Ghee Halwa (150g)',
    tamilName: 'திருநெல்வேலி நெய் அல்வா',
    restaurant: 'Iruttu Kadai Halwa Store',
    city: 'Tirunelveli',
    category: 'Sweets',
    price: 55,
    marketPrice: 95,
    kcal: 290,
    image: 'https://images.unsplash.com/photo-1571167530149-c8f32e2b6f6d?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Mild',
    description: 'Crafted with perennial Thamirabarani river water, whole wheat milk, and country cow ghee, caramelized to a warm, translucent glossy perfection.',
    portion: '150g warm sealed box',
    protein: 4,
    carbs: 46,
    fat: 11,
    availableAddons: [
      { name: 'Extra Roasted Cashew Studs', price: 15 },
      { name: 'Gift Box Packaging', price: 15 },
    ],
    tags: ['Melt in Mouth', 'Tirunelveli Heritage', 'GI Tag'],
  },
  {
    id: 'dish-22',
    name: 'Thanjavur Palace Rava Kesari',
    tamilName: 'தஞ்சாவூர் ரவா கேசரி',
    restaurant: 'Thanjavur Sapadu',
    city: 'Thanjavur',
    category: 'Sweets',
    price: 40,
    marketPrice: 70,
    kcal: 220,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Silken semolina roasted in ghee with golden raisins, whole cashew kernels, and natural saffron essence, honoring Thanjavur palace sweet heritage.',
    portion: '140g warm sweet cup',
    protein: 4,
    carbs: 34,
    fat: 7,
    availableAddons: [
      { name: 'Extra Roasted Dry Fruits', price: 15 },
    ],
    tags: ['Temple Recipe', 'Royal Sweet'],
  },
  {
    id: 'dish-23',
    name: 'Traditional Paal Payasam',
    tamilName: 'பால் பாயாசம்',
    restaurant: 'Paati Veedu',
    city: 'Chennai',
    category: 'Sweets',
    price: 45,
    marketPrice: 80,
    kcal: 210,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Slow-simmered reduced farm milk with Kerala raw red rice, green cardamom pods, and ghee-roasted cashews.',
    portion: '1 bowl chilled or warm',
    protein: 6,
    carbs: 32,
    fat: 6,
    availableAddons: [
      { name: 'Roasted Almond Slivers', price: 12 },
    ],
    tags: ['Comfort Sweet', 'Pure Milk'],
  },

  // --- DRINKS CATEGORY ---
  {
    id: 'dish-24',
    name: 'Kumbakonam Degree Filter Coffee',
    tamilName: 'கும்பகோணம் டிகிரி காபி',
    restaurant: 'Kumbakonam Degree Coffee',
    city: 'Salem',
    category: 'Drinks',
    price: 25,
    marketPrice: 50,
    kcal: 110,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Mild',
    description: 'Freshly roasted plantation peaberry coffee beans, slow-dripped first-degree decoction, blended with unadulterated boiling cow milk and organic cane sugar in brass davarah.',
    portion: 'Served in traditional Brass Davarah Tumbler',
    protein: 4,
    carbs: 14,
    fat: 3,
    availableAddons: [
      { name: 'Extra Strong Decoction Shot', price: 8 },
      { name: 'Organic Jaggery Sweetener', price: 5 },
    ],
    tags: ['Morning Ritual', 'Signature Decoction', 'Bestseller'],
  },
  {
    id: 'dish-25',
    name: 'Special Royal Madurai Jigarthanda',
    tamilName: 'மதுரை ஸ்பெஷல் ஜிகர்தண்டா',
    restaurant: 'Famous Madurai Jigarthanda',
    city: 'Madurai',
    category: 'Drinks',
    price: 60,
    marketPrice: 110,
    kcal: 250,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    isBestseller: true,
    spiceLevel: 'Mild',
    description: 'The royal cooling drink made with natural Badam Pisin (almond gum), concentrated reduced milk, nannari syrup, and topped with rich home-churned basundi ice cream.',
    portion: '300 ml chilled tall serving',
    protein: 7,
    carbs: 36,
    fat: 7,
    availableAddons: [
      { name: 'Extra Basundi Cream Scoop', price: 20 },
      { name: 'Natural Almond Gum Float', price: 12 },
    ],
    tags: ['Heritage Drink', 'Natural Cooling', 'Royal Recipe'],
  },
  {
    id: 'dish-26',
    name: 'Nannari Herbal Sarbath',
    tamilName: 'நன்னாரி சர்பத்',
    restaurant: 'Paati Veedu',
    city: 'Chennai',
    category: 'Drinks',
    price: 30,
    marketPrice: 60,
    kcal: 85,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Refreshing herbal cooler crafted from wild sarsaparilla root decoction, freshly squeezed key lime, and chilled mineral water with soaked basil seeds.',
    portion: '350 ml chilled glass',
    protein: 1,
    carbs: 20,
    fat: 0,
    availableAddons: [
      { name: 'Sabja (Sweet Basil) Float', price: 8 },
      { name: 'Extra Key Lime Zing', price: 5 },
    ],
    tags: ['100% Herbal', 'Body Cooler', 'Light Pick'],
  },
  {
    id: 'dish-27',
    name: 'Spiced Neer Mor (Buttermilk)',
    tamilName: 'தாளித்த நீர் மோர்',
    restaurant: 'Saravana Bhavan',
    city: 'Chennai',
    category: 'Drinks',
    price: 20,
    marketPrice: 40,
    kcal: 50,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=85',
    isVeg: true,
    spiceLevel: 'Mild',
    description: 'Refreshing churned country buttermilk tempered with crushed ginger, green chillies, asafoetida, fresh coriander, and curry leaves. Ultimate gut cooler.',
    portion: '300 ml earthen cup',
    protein: 3,
    carbs: 5,
    fat: 2,
    availableAddons: [
      { name: 'Extra Ginger Zing', price: 5 },
    ],
    tags: ['Zero Sugar', 'Probiotic', 'Hydration Hero'],
  },
]

export const COUPONS: Coupon[] = [
  {
    code: 'FIRSTBITE',
    title: 'First Conscious Order',
    description: '20% off on your first order up to ₹50',
    discountType: 'percent',
    discountValue: 20,
    minOrder: 100,
    maxDiscount: 50,
  },
  {
    code: 'MINDFUL50',
    title: 'Mindful Eater Reward',
    description: 'Flat ₹30 off on conscious orders over ₹150',
    discountType: 'flat',
    discountValue: 30,
    minOrder: 150,
  },
  {
    code: 'FREEDEL',
    title: 'Zero Delivery Fee',
    description: 'Free delivery on all kitchen orders above ₹149',
    discountType: 'free_delivery',
    discountValue: 25,
    minOrder: 149,
  },
  {
    code: 'TAMILNADU',
    title: 'State Heritage Celebration',
    description: '15% off up to ₹40 for authentic cuisine lovers',
    discountType: 'percent',
    discountValue: 15,
    minOrder: 120,
    maxDiscount: 40,
  },
]

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Sundari Raghavan',
    location: 'Mylapore, Chennai',
    rating: 5,
    date: '2 days ago',
    comment: 'Real Tamil Nadu price! The Ghee Podi Idli is only ₹65, whereas Zomato charges ₹120. Delivered steaming hot in minutes, and the doorbell sound when Murugan arrived was so delightful!',
    dishOrdered: 'Ghee Podi Idli (14 mini)',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'rev-2',
    author: 'Karthik Senthil',
    location: 'RS Puram, Coimbatore',
    rating: 5,
    date: 'Yesterday',
    comment: 'Authentic Kongu Kozhi curry with bun parotta. The delivery took only 1-2 minutes in the simulation and I acknowledged it right when the doorbell rang. Incredible concept!',
    dishOrdered: 'Kongu Nattu Kozhi Curry',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'rev-3',
    author: 'Meenakshi Sundaram',
    location: 'Anna Nagar, Madurai',
    rating: 5,
    date: '3 days ago',
    comment: 'The picture of Bun Parotta actually looks like Madurai Bun Parotta now! Prices are totally fair, and I love seeing exactly how much money and calories I saved.',
    dishOrdered: 'Madurai Bun Parotta (2 pcs) with Salna',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
  },
]

export const MINDFUL_REFLECTIONS = [
  {
    quote: 'Food eaten with calm awareness nourishes both body and mind.',
    source: 'Tirukkural — Chapter on Balanced Food',
  },
  {
    quote: 'Listen to your body before your senses. Real hunger is patient.',
    source: 'Siddha Wisdom',
  },
  {
    quote: 'Oru Vaati: Even a single pause before eating brings peace.',
    source: 'Mindful Dining Principle',
  },
]
